const QUICKDOT_APP_SHELL = [
  "./",
  "./index.html",
  "./admin.html",
  "./health.html",
  "./admin.css",
  "./styles.css",
  "./base.css",
  "./layout.css",
  "./panels.css",
  "./controls.css",
  "./entries.css",
  "./dialogs.css",
  "./responsive.css",
  "./quickdot-files.js",
  "./constants.js",
  "./dates.js",
  "./i18n.js",
  "./migrations.js",
  "./state.js",
  "./dom.js",
  "./core.js",
  "./entry-normalize.js",
  "./sync-store.js",
  "./storage.js",
  "./preferences-store.js",
  "./sync-ui.js",
  "./sync-auth.js",
  "./sync-diagnostics.js",
  "./sync-payload.js",
  "./sync-normalized.js",
  "./sync.js",
  "./entry-store.js",
  "./entry-swipe.js",
  "./entry-drag.js",
  "./entries.js",
  "./render-static.js",
  "./render-shell.js",
  "./render-entries.js",
  "./render-logs.js",
  "./render-calendar.js",
  "./render.js",
  "./navigation-events.js",
  "./entry-events.js",
  "./app-events.js",
  "./app.js",
  "./admin.js",
  "./supabase-config.js",
  "./manifest.webmanifest",
  "./icons/icon.svg",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
];

const QUICKDOT_CHECK_JS = [
  "quickdot-files.js",
  "admin.js",
  "constants.js",
  "dates.js",
  "i18n.js",
  "migrations.js",
  "state.js",
  "dom.js",
  "core.js",
  "entry-normalize.js",
  "sync-store.js",
  "storage.js",
  "preferences-store.js",
  "sync-ui.js",
  "sync-auth.js",
  "sync-diagnostics.js",
  "sync-payload.js",
  "sync-normalized.js",
  "sync.js",
  "entry-store.js",
  "entry-swipe.js",
  "entry-drag.js",
  "entries.js",
  "render-static.js",
  "render-shell.js",
  "render-entries.js",
  "render-logs.js",
  "render-calendar.js",
  "render.js",
  "navigation-events.js",
  "entry-events.js",
  "app-events.js",
  "app.js",
  "sw.js",
];

const QUICKDOT_TEST_FILES = [
  "tests/smoke-test.js",
  "tests/data-logic-test.js",
  "tests/seed-cleanup-test.js",
  "tests/entry-actions-test.js",
  "tests/sync-maintenance-test.js",
  "tests/scroll-preservation-test.js",
  "tests/sync-auth-ui-test.js",
  "tests/i18n-labels-test.js",
];

const QUICKDOT_DEPLOY_FILES = [
  ...QUICKDOT_APP_SHELL.filter((file) => file !== "./").map((file) => file.replace("./", "")),
  "sw.js",
  "supabase-schema.sql",
  "README.md",
];

if (typeof self !== "undefined") {
  self.QUICKDOT_APP_SHELL = QUICKDOT_APP_SHELL;
}

if (typeof module !== "undefined") {
  module.exports = {
    QUICKDOT_APP_SHELL,
    QUICKDOT_CHECK_JS,
    QUICKDOT_TEST_FILES,
    QUICKDOT_DEPLOY_FILES,
  };
}
