// QuickDot state module. Loaded by index.html.
const state = {
  entries: [],
  deletedEntries: [],
  symbolMeanings: { ...defaultSymbolMeanings },
  language: defaultLanguage,
  collapseState: {
    calendar: false,
    symbols: false,
  },
  view: "daily",
  selectedDate: toDateKey(new Date()),
  calendarMonth: startOfMonth(new Date()),
  search: "",
  searchOpen: false,
  expandedDateCards: new Set(),
  expandedSubitems: new Set(),
  pendingMigrationId: null,
  pendingCopyId: null,
  pendingSubitemId: null,
  pendingEditId: null,
  pendingDelete: null,
  entrySwipe: null,
  dragSort: null,
  supabaseClient: null,
  syncSession: null,
  syncQueue: [],
  syncErrorQueue: [],
  syncDebounce: null,
  syncRefreshInterval: null,
  syncBusyCount: 0,
  syncBackoffMs: 0,
  lastSyncAttemptAt: 0,
  normalizedSyncAvailable: null,
  suppressDirty: false,
};
